added -e script argument to give config file to script

diff --git a/undeploy b/undeploy
--- a/undeploy
+++ b/undeploy
@@ -23,6 +23,7 @@ function showUsage {
     echo ""
     echo "   Usage $0 <Project name>"
     echo ""
+    echo "      -e | --envfile Environnement file (default is ${GREEN}config.env${NC})"
     echo "      -h | --help show this help"
     echo ""
     echo "      !!! This script requires docker and docker-compose !!!"
@@ -33,6 +34,16 @@ function showUsage {
 while (( "$#" ));
 do
 	case "$1" in
+        -e|--envfile)
+            if [[ "$2" == "" || ${2:0:1} == "-" ]]; then
+                showUsage
+                echo -e "${RED}[ERROR] Missing config file name${NC}"
+                echo -e ""
+                exit 1
+            fi
+            ENV_FILE="$2"
+            shift 2 # past argument
+            ;;
         -h|--help)
             showUsage
             shift # past argument
@@ -62,6 +73,17 @@ if [ "${PROJECT_NAME}" == "" ]; then
     exit 0
 fi
 
+#
+# The environement file is mandatory
+# It contains all configuration to build and run resto images
+#
+if [[ ! -f ${ENV_FILE} ]]; then
+    showUsage
+    echo -e "${RED}[ERROR] The \"${ENV_FILE}\" file does not exist!${NC}"
+    echo ""
+    exit 1
+fi
+
 echo "[INFO] Stopping ${GREEN}${PROJECT_NAME}${NC} docker instance"
 
 # manages list of containers to bring down
@@ -78,7 +100,6 @@ COMPOSE_FILE=${COMPOSE_FILE} docker-compose --project-name ${PROJECT_NAME} down
 
 echo "[INFO] Done !"
 echo ""
-    
 
 
 
